// Action types
export const SET_USER_DOCUMENTS = "SET_USER_DOCUMENTS";
export const GET_DOCUMENT = "GET_DOCUMENT";
export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const EDIT_DOCUMENT = "EDIT_DOCUMENT";
